### ISSUE TITLE
Stand up team code review.

### ISSUE THREAD

**Issue by pipe2442** [balerum03/smashing-heatmap#2]
Guys you did an awesome job!!! congrats you are so talented. Just a few things, try to give gray color also to the images remember that this is a gray scale model, also try to give color to more of the boxes in the page the idea its to identify each element with a great color and in the future you can work with responsiveness, great job!

**Comment by abredi** [comment]
fixed: @pipe244, We fixed all the issues stated by you. Thanks for your humble words.
